cars:
  - brand: Ford
    model: Probe
  - brand: Hyundai
    model: Coupe
  - brand: Hyundai
    model: Tiburon
  - brand: Hyundai
    model: Tuscani
  - brand: Mitsubishi
    model: Eclipse
    generations:
      - 3G
  - brand: Toyota
    model: Celica
