cars:
  - brand: Audi
    model: TT
    generations:
      - 8N
      - 8N · Рестайлинг
  - brand: Chevrolet
    model: Cavalier
    body_types:
      - купе
  - brand: Chrysler
    model: Sebring
    generations:
      - II
    body_types:
      - купе
      - кабриолет
  - brand: Dodge
    model: Stratus
    generations:
      - II
      - II · Рестайлинг
    body_types:
      - купе
  - brand: Ford
    model: Cougar
  - brand: Ford
    model: Probe
  - brand: Hyundai
    model: Coupe
    generations:
      - RD · Рестайлинг
      - GK
      - GK F, L2 · Рестайлинг
  - brand: Hyundai
    model: Genesis coupe
  - brand: Hyundai
    model: Tiburon
    generations:
      - RD · Рестайлинг
      - GK
      - GK F, L2 · Рестайлинг
  - brand: Hyundai
    model: Tuscani
  - brand: Mitsubishi
    model: Eclipse
    generations:
      - 3G
      - 4G
  - brand: Toyota
    model: Camry Solara
    generations:
      - XV30
  - brand: Toyota
    model: Celica
    generations:
      - VII (T230)
      - VII (T230) · Рестайлинг