cars:
  - brand: Audi
    model: TT
    generation: 8N
  - brand: Audi
    model: TT
    generation: 8N · Рестайлинг
  - brand: Audi
    model: A5
    generation: 8T
  - brand: Audi
    model: A1
    generation: 8X
  - brand: Infiniti
    model: G
    generation: III
  - brand: Mitsubishi
    model: Lancer
    generation: X
  - brand: Mitsubishi
    model: Lancer
    generation: X · Рестайлинг
  - brand: Mitsubishi
    model: Eclipse
    generation: 3G
  - brand: Mitsubishi
    model: Eclipse
    generation: 4G
  - brand: Ford
    model: Mustang
    generation: IV · Рестайлинг
  - brand: Toyota
    model: Celica
    generation: VII (T230)
  - brand: Toyota
    model: Celica
    generation: VII (T230) · Рестайлинг
  - brand: Chrysler
    model: Sebring
    generation: II
  - brand: Hyundai
    model: Tiburon
    generation: RD · Рестайлинг
  - brand: Hyundai
    model: Tiburon
    generation: GK
  - brand: Hyundai
    model: Tiburon
    generation: GK F, L2 · Рестайлинг
  - brand: Hyundai
    model: Tuscani
  - brand: Hyundai
    model: Genesis coupe
  - brand: Honda
    model: CR-Z
  - brand: Jaguar
    model: X-Type
  - brand: Jaguar
    model: S-Type
  - brand: Alfa Romeo
    model: 159
  - brand: Mazda
    model: 3
    generation: BK
  - brand: Mazda
    model: 3
    generation: BK · Рестайлинг
  - brand: Dodge
    model: Intrepid
    generation: II
  - brand: Dodge
    model: Stratus
    generation: II
  - brand: Dodge
    model: Stratus
    generation: II · Рестайлинг
  - brand: Honda
    model: Civic
    generation: VII
  - brand: Honda
    model: Civic
    generation: VIII
  - brand: Honda
    model: Civic
    generation: VIII · Рестайлинг


