cars:
  - brand: Audi
    model: TT
    generations:
      - 8N
      - 8N · Рестайлинг
  - brand: Audi
    model: A5
    generations:
      - 8T
    body_types:
      - купе
  - brand: Audi
    model: A1
    generations:
      - 8X
  - brand: Infiniti
    model: G
    generations:
      - III
    body_types:
      - купе
  - brand: Mitsubishi
    model: Lancer
    generations:
      - X
      - X · Рестайлинг
  - brand: Mitsubishi
    model: Eclipse
    generations:
      - 3G
      - 4G
  - brand: Ford
    model: Mustang
    generations:
      - IV · Рестайлинг
  - brand: Toyota
    model: Celica
    generations:
      - VII (T230)
      - VII (T230) · Рестайлинг
  - brand: Toyota
    model: Camry Solara
    generations:
      - XV30
  - brand: Chrysler
    model: Sebring
    generations:
      - II
    body_types:
      - купе
      - кабриолет
  - brand: Hyundai
    model: Tiburon
    generations:
      - RD · Рестайлинг
      - GK
      - GK F, L2 · Рестайлинг
  - brand: Hyundai
    model: Tuscani
  - brand: Hyundai
    model: Genesis coupe
  - brand: Hyundai
    model: Coupe
    generations:
      - RD · Рестайлинг
      - GK
      - GK F, L2 · Рестайлинг
  - brand: Honda
    model: CR-Z
  - brand: Jaguar
    model: X-Type
  - brand: Jaguar
    model: S-Type
  - brand: Alfa Romeo
    model: 159
  - brand: Mazda
    model: 3
    generations:
      - BK
      - BK · Рестайлинг
  - brand: Dodge
    model: Intrepid
    generations:
      - II
  - brand: Dodge
    model: Stratus
    generations:
      - II
      - II · Рестайлинг
    body_types:
      - купе
  - brand: Volkswagen
    model: Scirocco
    generations:
      - III
  - brand: Chevrolet
    model: Cavalier
    body_types:
      - купе
  - brand: Ford
    model: Cougar