# This workflow will install Python dependencies, run app
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run the app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install package
        run: make install
      - name: run codecheck
        run: make check

  collect_data:
    runs-on: ubuntu-latest
    needs: code_check
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install package
        run: make install_prod
      - name: Create results folder
        run: mkdir -p dumps
      - name: Collect data
        run: cars collecting collect
      - name: Save results
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: output/result.txt
